version: "3"

services:

  cli0:
    image: kiang/neo-cli-privatenet:v2.10.2
    container_name: cli0
    ports:
    - "10331-10334:10331-10334"
    networks:
    - nodeLink
    volumes:
    - "/data/cli0:/neo/data"
    command: expect /neo/scripts/run.sh 0
    stdin_open: true
    tty: true

  cli1:
    image: kiang/neo-cli-privatenet:v2.10.2
    container_name: cli1
    ports:
    - "20331-20334:10331-10334"
    networks:
    - nodeLink
    volumes:
    - "/data/cli1:/neo/data"
    command: expect /neo/scripts/run.sh 1
    stdin_open: true
    tty: true
    depends_on:
    - cli0

  cli2:
    image: kiang/neo-cli-privatenet:v2.10.2
    container_name: cli2
    ports:
    - "30331-30334:10331-10334"
    networks:
    - nodeLink
    volumes:
    - "/data/cli2:/neo/data"
    command: expect /neo/scripts/run.sh 2
    stdin_open: true
    tty: true
    depends_on:
    - cli1

  cli3:
    image: kiang/neo-cli-privatenet:v2.10.2
    container_name: cli3
    ports:
    - "40331-40334:10331-10334"
    networks:
    - nodeLink
    volumes:
    - "/data/cli3:/neo/data"
    command: expect /neo/scripts/run.sh 3
    stdin_open: true
    tty: true
    depends_on:
    - cli2

  neo-scan-privatenet:
    image: kiang/neo-scan-privatenet
    container_name: neo-scan-privatenet
    ports:
    - 4000:4000
    networks:
    - nodeLink
    links:
    - postgres
    - cli0
    - cli1
    - cli2
    - cli3
    depends_on:
    - postgres
    - cli0
    - cli1
    - cli2
    - cli3

  postgres:
    image: postgres:10.1
    container_name: postgres
    networks:
    - nodeLink
    ports:
    - 5432:5432
    environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres

networks:
  nodeLink:
    driver: bridge

